name: Build MSI packages for Windows
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Test MSI major upgrade
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test MSI major upgrade
        run: .github/scripts/msi-test-install-upgrade.ps1